#!/bin/bash

# Access your clipboard on the command line
# usage:
#  ./clipboard
#    will output current contents of klipper
#  echo "foobar" | ./clipboard
#    will put "foobar" into your clipboard/klipper

if [ -z "$(which xclip)" ]; then
    echo "xclip isn't installed"
    exit 1
fi

readCmd="xclip -o -selection clipboard"
writeCmd="xclip -i -selection clipboard"

# set uri-list as mimetype to paste files
if [ "$1" = "uri" ]; then
    writeCmd="$writeCmd -t text/uri-list"
fi

# check for stdin
if ! test -t 0; then
  # oh, nice - user input! we set that as current clipboard content
  $writeCmd < /dev/stdin
  exit
fi

# if we reach this point no user input was given and we
# print out the current contents of the clipboard
$readCmd
