#!/bin/bash
#
# find files called e.g. libFoo.so.1.2.3
# that have newer replacements. The newer files
# are checked by looking at where libFoo.so links
#

dir="."

if [ ! -z "$1" ]; then
    dir="$1/"; # trailing slash to enter symlinked folders
fi

find "$dir" -type f -name "*.so.*" | while read f; do
    base=$(echo $f | sed 's/.so.*$/.so/');
    if [[ ! -f "$base" ]]; then
        base=$(echo $f | sed -E 's/\.so\.([0-9])\..+$/.so.\1/');
    fi
    if [[ -f "$base" && "$(readlink -f $base)" != "$(readlink -f $f)" ]]; then
        echo $f;
    fi
done
