#!/bin/bash
if [[ "$1" == "" ]]; then
    echo "no path given"
    exit 255
fi

url="$1"

if [[ "$2" == "" ]]; then
    dir=`basename $1`
else
    dir="$2"
fi

if [[ -d "$dir" ]]; then
    echo "dir $dir exists"
    exit 255
fi

echo -n "getting svn rev to checkout... "
rev=$(svn log -l 100 "$url" |  egrep -o "^r[0-9]+" | cut -d "r" -f 2 | tail -n 1)

if [[ "$rev" == "" ]]; then
    echo "error"
    echo "url $url seems to be invalid"
    exit 255
fi

echo "found $rev"

echo "stetting up git-svn"

mkdir -p "$dir"
cd "$dir"

echo "git svn init "$url""
git svn init "$url"
echo "git svn fetch -r $rev"
git svn fetch -r $rev
echo "git svn rebase"
git svn rebase
