#!/bin/bash

tagFrom=$1
tagTo=$2

if [[ "$tagFrom" == "" || "$tagTo" == "" ]]; then
  echo "$0 FROM TO";
  exit
fi

revFrom=$(git log --pretty=oneline -1 $tagFrom | awk '{print $1}')
revTo=$(git log --pretty=oneline -1 $tagTo | awk '{print $1}')

headline="ChangeLog for $(basename $(pwd)) $tagTo"
echo $headline
echo $headline | sed 's/./=/g'
echo

for rev in $(git log --no-merges --pretty=oneline $revFrom..$revTo | egrep -v "(SVN_SILENT|^[mM]erge)" | awk '{print $1}');
#for rev in $(git log --pretty=oneline $revFrom..$revTo | egrep -v "(SVN_SILENT)" | awk '{print $1}');
do
  git --no-pager log -1 --pretty=format:"* %an: %s%n" $rev
done

#kate: indent-width 2; replace-tabs on;
