#!/bin/bash

request=$1

if [[ "$request" == "" ]]; then
  echo "$0 REQUEST"
  exit 1
fi

branch=$(git branch | grep '*' | awk '{print $2}')

if [[ "$branch" == "" ]]; then
  echo "invalid branch - are you in the correct directory?"
  exit 2
fi

url=$(git remote -v | egrep '\(fetch\)$' | awk '{print $2}')
if [[ "$url" == "" ]]; then
  echo "could not find pull url"
  exit
fi

echo
echo -n "you are going to merge the merge request #$request into branch $branch - correct? [y/N] "

read input

if [[ "$input" != "y" ]]; then
  echo "bye bye"
  exit
fi

newBranch=merge-request-$request

git checkout -b $newBranch || exit

function resetAndExit()
{
  git checkout $branch
  git branch -D $newBranch
  exit
}

echo

git pull $url refs/merge-requests/$request || resetAndExit

echo
echo "commits that will be merged:"

git log --pretty=oneline --abbrev-commit $branch..$newBranch

echo
echo -n "continue? [y/N] "
read input

if [[ "$input" != "y" ]]; then
  resetAndExit
fi

echo
git checkout $branch
echo
git merge $newBranch -m "merge request #$request"

resetAndExit

echo
echo "run git push to finalize merge"

