#!/bin/bash

#$KDE_SRC/extragear/utils/kdesrc-build/kdesrc-build --debug --stop-on-failure --ignore-modules=cmake-git $@
$KDE_SRC/extragear/utils/kdesrc-build/kdesrc-build --stop-on-failure --ignore-modules=plymouth-kcm $@
