#!/bin/bash


if [[ "$(pwd)" != "$HOME/projects/"* ]]; then
  echo "$(pwd) is not subfolder of $HOME/projects prefix"
  exit 1
fi

function trycompile()
{

  if [ -f Makefile ]; then
    /usr/bin/make $@
  elif [ -f build.ninja ]; then
    /usr/bin/ninja $@
  else
    return 1
  fi
}

trycompile && exit 0
cb > /dev/null

while true; do
  trycompile && exit 0
  if [[ "$(pwd)" == "$HOME/projects/"* ]]; then
    cd ..
  else
    echo "no build info found"
    exit 1
  fi
done
