#!/bin/bash
#
# This program uses the pastebinit program and a KDE4 klipper instance
# to paste fast and conveniently from a console.

# see man pastebinit and it's -b argument
target="http://mwolff.pastebin.com"

# see man pastebinit and it's -f argument
formatting="text"

if [[ "$1" != "" ]]; then
	formatting="$1"
fi

# get clipboard contents from klipper
toPaste=$(dbus-send --print-reply --dest=org.kde.klipper /klipper \
    org.kde.klipper.klipper.getClipboardContents | awk '
        BEGIN { output = ""; }
        {
            if ( NR > 1 ) {
                output = output $0 "\n";
            }
        }
        END {
            print substr(output, 12, length(output) - 13);
        }')

if [[ "$(echo $toPaste | wc -l)" == "1" && "$(echo $toPaste | grep $target)" ]]; then
  echo "cancelling, not pasting '$toPaste' - looks useless"
fi

# paste
echo "will paste the following to $target:"
echo
echo $toPaste
echo
echo -n "... pasting ..."

pasteUrl=$(echo -n "$toPaste" | pastebinit -f "$formatting" -b "$target")

echo " done"
echo
echo "pasted to $pasteUrl"

# set klipper contents to pasteUrl
dbus-send --type=method_call --dest=org.kde.klipper \
    /klipper org.kde.klipper.klipper.setClipboardContents \
        string:"$pasteUrl"
