#!/bin/bash

echo 1 | sudo tee /proc/sys/kernel/sched_schedstats

perf record \
    --event sched:sched_stat_iowait/call-graph=fp/ \
    --event sched:sched_process_exit/call-graph=fp/ \
    --event sched:sched_switch/call-graph=dwarf/ \
    --output perf.data.raw $@

echo 0 | sudo tee /proc/sys/kernel/sched_schedstats

perf inject --sched-stat --input perf.data.raw --output perf.data
